# Generated by Django 5.1.1 on 2024-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ratings',
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1200),
        ),
    ]
