# Generated by Django 5.1.1 on 2024-09-21 19:41

import django.contrib.postgres.fields
import lobbies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=lobbies.models.GameLobby.generate_identifier, max_length=8, unique=True)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('spectators', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
