# Generated by Django 5.1.1 on 2024-09-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelobby',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
