# Generated by Django 5.1.1 on 2024-10-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0002_alter_gamelobby_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelobby',
            name='connect_url',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
