# Generated by Django 5.1.1 on 2024-09-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='player1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='player2',
            field=models.CharField(max_length=150),
        ),
    ]
