# Generated by Django 5.1.1 on 2024-11-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_player1_gamerecord_black_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='finished_at',
            field=models.DateTimeField(),
        ),
    ]
